apiVersion: apps/v1
kind: Deployment
metadata:
  name: egress-router
  labels:
    app: egress-router
spec:
  replicas: 3
  selector:
    matchLabels:
      app: egress-router
  template:
    metadata:
      labels:
        app: egress-router
    spec:
      containers:
      - name: egress-router
        image: ghcr.io/${IMAGE_NAME}:main
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1000Mi"
            cpu: "1000m"
          limits:
            memory: "1000Mi"
            cpu: "1000m"
        ports:
        - containerPort: 80